/** 100 teaching quotes. One is selected deterministically per day. */
export const TEACHING_QUOTES: string[] = [
  "Every student carries a piece of your teaching into the future.",
  "A teacher plants seeds that grow forever.",
  "You are not just teaching lessons, you are shaping lives.",
  "The best teachers teach from the heart, not from the book.",
  "Behind every confident student stands a patient teacher.",
  "Teaching is the art of awakening curiosity.",
  "Your patience today becomes someone's courage tomorrow.",
  "Small lessons, repeated daily, build extraordinary futures.",
  "A good teacher can change a life in a single sentence.",
  "You teach more by who you are than by what you say.",
  "Every question a student asks is a door you helped open.",
  "The influence of a teacher never truly ends.",
  "Teaching is the one profession that creates all others.",
  "Knowledge shared is knowledge multiplied.",
  "A classroom is a place where futures quietly begin.",
  "You measure success in students, not in numbers.",
  "Great teachers make hard things feel possible.",
  "Learning is the gift you give again and again.",
  "One encouraging word can outlive a lifetime of doubt.",
  "Teachers turn effort into achievement.",
  "The mind you shaped today will shape the world tomorrow.",
  "Every attendance mark is a moment of growth recorded.",
  "Consistency is the quietest form of greatness.",
  "You are the reason someone believes in themselves.",
  "Teaching is love made visible through effort.",
  "The greatest lessons are taught by example.",
  "You give students not answers, but the courage to seek them.",
  "Progress is made of small, patient steps.",
  "Every child deserves someone who refuses to give up on them.",
  "Your work echoes in classrooms you will never see.",
  "Teaching is planting hope in fertile minds.",
  "A student's success is a teacher's quiet reward.",
  "Wisdom grows when it is shared freely.",
  "Discipline taught with kindness lasts a lifetime.",
  "The best classrooms are built on trust.",
  "You are writing chapters in stories you'll never finish reading.",
  "Curiosity is the spark; you are the flame.",
  "Teaching is the gentle art of building confidence.",
  "Every lesson is a bridge to a bigger world.",
  "You turn 'I can't' into 'I did'.",
  "A teacher's belief is a student's foundation.",
  "The smallest encouragement can change a direction.",
  "Learning never ends, and neither does your influence.",
  "You give time, and time gives back generations.",
  "Teaching is the quiet work that changes everything.",
  "A great teacher makes learning feel like discovery.",
  "You are remembered for how you made students feel.",
  "Every family that trusts you honours your work.",
  "The best teachers keep learning too.",
  "Kindness in the classroom builds character outside it.",
  "You are shaping thinkers, not just test scores.",
  "Effort repeated becomes excellence.",
  "One teacher can light a hundred lamps.",
  "Your classroom is a workshop for dreams.",
  "Teaching is listening as much as speaking.",
  "Every day you show up, someone grows.",
  "You make complicated things simple and simple things beautiful.",
  "Learning happens where patience lives.",
  "A student's confidence is your finest creation.",
  "Behind every skill is a teacher who cared.",
  "You are building minds one honest conversation at a time.",
  "Great teaching is invisible, its results are not.",
  "Your encouragement is someone's inner voice one day.",
  "Teaching is generosity practiced daily.",
  "The lessons stay long after the notes are lost.",
  "You help students find what they are good at.",
  "A calm teacher creates a brave student.",
  "Every mistake corrected gently becomes a strength.",
  "You are the steady presence in someone's growing years.",
  "Teaching is turning potential into practice.",
  "A single explanation can unlock a lifetime of interest.",
  "You give children a reason to look forward to tomorrow.",
  "Growth is slow, then suddenly obvious.",
  "Your work is measured in futures, not hours.",
  "Teachers are the architects of possibility.",
  "You teach students how to think, not what to think.",
  "Patience is the highest form of teaching.",
  "Every hour you teach becomes a habit in someone's life.",
  "The best reward is watching a student outgrow you.",
  "You make learning feel safe.",
  "Real teaching begins where fear ends.",
  "A teacher's words become a student's inner strength.",
  "You are proof that ordinary days build extraordinary lives.",
  "Teaching is hope in action.",
  "The classroom is small; its impact is not.",
  "You are shaping the adults of tomorrow.",
  "Every student remembers the teacher who believed first.",
  "Consistency turns learners into achievers.",
  "You give clarity where there was confusion.",
  "Teaching is the longest lasting kindness.",
  "Your effort compounds quietly over years.",
  "A teacher never knows where their influence stops.",
  "You are the reason learning feels possible.",
  "Every family trusts you with their most precious hope.",
  "Great teachers create independent learners.",
  "You turn routine into progress.",
  "The world improves one taught mind at a time.",
  "You are building tomorrow, one lesson at a time.",
  "Teaching is the quiet courage of showing up daily.",
  "Every number here is a life you touched.",
  "Your teaching legacy is written in people, not in records.",
];

/** Deterministic day-of-year selection: same quote for everyone, changes daily. */
export function quoteOfTheDay(date = new Date()): string {
  const start = Date.UTC(date.getFullYear(), 0, 0);
  const now = Date.UTC(date.getFullYear(), date.getMonth(), date.getDate());
  const dayOfYear = Math.floor((now - start) / 86_400_000);
  return TEACHING_QUOTES[dayOfYear % TEACHING_QUOTES.length];
}
